[package]
name = "omniglot-example-add"
version.workspace = true
edition = "2021"

[build-dependencies]
bindgen.workspace = true
cc = "1.2.44"

[dependencies]
omniglot = { path = "../../omniglot" }
env_logger = "0.11.8"
